### ISSUE TITLE
Add snmp_exporter

### ISSUE THREAD

**Issue by victorock** [3scale-ops/prometheus-exporter-operator#14]
Add snmp_exporter

**Comment by slopezz** [comment]
Hi @victorock , thanks for reaching us!

Can you provdfe more details about what  you expect from this exporter, with examples of how to deploy it on k8s, configmap example... so we can easily add support to snmp_exporter to the operator?

**Comment by victorock** [comment]
Hello @slopezz, i ll try to create a draft... and create another issue with some refactoring of folder structure, to better accommodate other exporters...

**Comment by slopezz** [comment]
Hi @victorock , are you still interested on snmp_exporter?

**Comment by johnsimcall** [comment]
I came here today specifically looking for snmp_exporter functionality

**Comment by raelga** [comment]
No more interest has been show on including this operator, closing until more evidence is provided.

/priority awaiting-more-evidence
/kind feature
/label size/m
/close
