### ISSUE TITLE
Add gpfs exporter

### ISSUE THREAD

**Issue by fycheng123** [3scale-ops/prometheus-exporter-operator#39]
Does prometheus-exporter-operator  support adding gpfs exporter

**Comment by raelga** [comment]
No more interest has been show on including this operator, closing until more evidence is provided.

/priority awaiting-more-evidence
/close

**Comment by raelga** [comment]
No more interest has been show on including this operator, closing until more evidence is provided.

/priority awaiting-more-evidence
/kind feature
/label size/m
/close
